%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_ConnectionAlreadyActive
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_ConnectionAlreadyActive').
-ic_compiled("4_4").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyActive:1.0",
                   "ConnectionAlreadyActive",[]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/ConnectionAlreadyActive:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_ConnectionAlreadyActive".



