%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ConsumerAdmin
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSNOTIFYCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


