%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullSupplier
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL, true).




-endif.


