%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotificationComm_Event
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONCOMM_EVENT_HRL).
-define(OE_COSNOTIFICATIONCOMM_EVENT_HRL, true).




-endif.


