%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_UTO
%% Source: /home/rickp/src/otolo/otp/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_UTO_HRL).
-define(COSTIME_UTO_HRL, true).




-endif.


