%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosTime
%% Source: /home/rickp/src/otolo/otp/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSTIME_HRL).
-define(OE_COSTIME_HRL, true).




-endif.


