%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_ProxyPushSupplier
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_PROXYPUSHSUPPLIER_HRL).
-define(COSNOTIFYCHANNELADMIN_PROXYPUSHSUPPLIER_HRL, true).




-endif.


