%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotification_QoSAdmin
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFICATION_QOSADMIN_HRL).
-define(COSNOTIFICATION_QOSADMIN_HRL, true).




-endif.


