%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullConsumer
%% Source: /home/rickp/src/otolo/otp/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLCONSUMER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLCONSUMER_HRL, true).




-endif.


