%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ProxyPushSupplier
%% Source: /home/rickp/src/otolo/otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL).
-define(COSEVENTCHANNELADMIN_PROXYPUSHSUPPLIER_HRL, true).




-endif.


