%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_ConsumerAdmin
%% Source: /home/rickp/src/otolo/otp/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL).
-define(COSEVENTCHANNELADMIN_CONSUMERADMIN_HRL, true).




-endif.


