%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CORBA
%% Source: /home/rickp/src/otolo/otp/lib/orber/src/CORBA.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_CORBA_HRL).
-define(OE_CORBA_HRL, true).




-endif.


