%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTransactions_Terminator
%% Source: /home/rickp/src/otolo/otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTRANSACTIONS_TERMINATOR_HRL).
-define(COSTRANSACTIONS_TERMINATOR_HRL, true).




-endif.


