%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP_Server
%% Source: /home/rickp/src/otolo/otp/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_SERVER_HRL).
-define(ETRAP_SERVER_HRL, true).




-endif.


